StartupEvents.registry("block", event => {
    event.create('torcherino')
        .soundType(SoundType.WOOD)
        .hardness(0.0)
        .resistance(0.0)
        .lightLevel(1.0)
        .renderType('cutout')
        .noCollision()
        .waterlogged()
        .box(6,0,6,10,10,10,true);

    event.create('nwither_plush')
        .soundType(SoundType.WOOL)
        .hardness(0.0)
        .resistance(0.0)
        .renderType('cutout')
        .box(4,0,4,12,14,10,true)
        .property(BlockProperties.HORIZONTAL_FACING)
    
    // event.create('mm:base_machine_block')
    //     .soundType('metal')
    //     .hardness(3)
    //     .resistance(4)
    //     .textureAll('mm:block/base_block')

    event.create('censer')
        .soundType(SoundType.STONE)
        .hardness(0)
        .resistance(0)
        .renderType('cutout')
        .box(5,0,5,11,15,11)
        .lightLevel(0.4)

    event.create('emendatusenigmatica:raw_iesnium_block')
        .soundType(SoundType.METAL)
        .hardness(3)
        .resistance(3)
        .tagBoth('forge:storage_blocks')
        .tagBoth(`forge:storage_blocks/raw_iesnium`)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool()
})