// priority: -1

ServerEvents.recipes(e => {
    e.replaceInput({}, 'ae2:calculation_processor', '#forge:processors/basic')
    e.replaceInput({}, 'ae2:logic_processor', '#forge:processors/improved')
    e.replaceInput({}, 'ae2:engineering_processor', '#forge:processors/advanced')
    e.replaceInput({}, 'ae2:formation_core', '#forge:construction_cores')
    e.replaceInput({}, 'ae2:annihilation_core', '#forge:destruction_cores')
    e.replaceInput({}, 'refinedstorage:basic_processor', '#forge:processors/basic')
    e.replaceInput({}, 'refinedstorage:improved_processor', '#forge:processors/improved')
    e.replaceInput({}, 'refinedstorage:advanced_processor', '#forge:processors/advanced')
    e.replaceInput({}, 'refinedstorage:construction_core', '#forge:construction_cores')
    e.replaceInput({}, 'refinedstorage:destruction_core', '#forge:destruction_cores')
    e.replaceInput({output: 'mysticalagriculture:infusion_altar'}, 'minecraft:stone', 'ars_nouveau:sourcestone')
    e.replaceInput({output: 'mysticalagriculture:infusion_pedestal'}, 'minecraft:stone', 'ars_nouveau:sourcestone')
    e.replaceInput({output: 'mekaweapons:mekatana'}, 'mekaweapons:katana_blade', 'epicsamurai:katana')
    e.replaceInput({mod: 'functionalstorage'}, 'minecraft:oak_planks', '#chipped:oak_planks')
    e.replaceInput({mod: 'functionalstorage'}, 'minecraft:spruce_planks', '#chipped:spruce_planks')
    e.replaceInput({mod: 'functionalstorage'}, 'minecraft:acacia_planks', '#chipped:acacia_planks')
    e.replaceInput({mod: 'functionalstorage'}, 'minecraft:birch_planks', '#chipped:birch_planks')
    e.replaceInput({mod: 'functionalstorage'}, 'minecraft:dark_oak_planks', '#chipped:dark_oak_planks')
    e.replaceInput({mod: 'functionalstorage'}, 'minecraft:jungle_planks', '#chipped:jungle_planks')
    e.replaceInput({mod: 'functionalstorage'}, 'minecraft:crimson_planks', '#chipped:crimson_planks')
    e.replaceInput({mod: 'functionalstorage'}, 'minecraft:warped_planks', '#chipped:warped_planks')
    e.replaceInput({mod: 'functionalstorage'}, 'minecraft:mangrove_planks', '#chipped:mangrove_planks')
    e.replaceInput({mod: 'functionalstorage'}, 'minecraft:cherry_planks', '#chipped:cherry_planks')
    e.replaceInput({id: 'create:sandpaper_polishing/rose_quartz'}, 'create:rose_quartz', '#create:rose_quartz')
    e.replaceInput({id: 'createaddition:compat/mekanism/rose_quartz_enriching'}, 'create:rose_quartz', '#create:rose_quartz')

})